# Generated by Django 2.0.1 on 2018-01-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=300)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('is_todo', models.BooleanField(default=False)),
                ('is_inprogress', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(verbose_name='date created')),
                ('list_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ToDoApp.ToDoList')),
            ],
        ),
    ]
