# Generated by Django 2.0.1 on 2018-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20180110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='date_finished',
            field=models.DateTimeField(default=None, verbose_name='date finished'),
        ),
    ]
